import { Inter } from "next/font/google";
import "@/app/ui/globals.css";
import { mulish } from "@/app/ui/fonts";
import SideNav from "../ui/sidenav";
import clsx from "clsx";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>

        <SideNav/>
        <main className={clsx(mulish.className, 'flex m-auto')} >{children}</main>

        
    </>
    
  );
}
