import "@/app/ui/globals.css";
import { mulish } from "@/app/ui/fonts";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={mulish.className}>{children}</body>
    </html>
  );
}
