export const meteoras =[
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        srcBlur:"/meteora1.png",
        src:"/Purple-Planet.png",
        alt:"planeta"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        srcBlur:"/meteora2.png",
        src:"/sun.png",
        alt:"planeta"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        srcBlur:"/meteora3.png",
        src:"/green.png",
        alt:"planeta"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        srcBlur:"/meteora4.png",
        src:"/blue.png",
        alt:"planeta",
    }

]