export const meteoras =[
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/Purple-Planet.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/Purple-Planet.png"
    }
    ,
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/Purple-Planet.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/Purple-Planet.png"
    }
]