export const meteoras =[
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/meteora1.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/meteora2.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/meteora3.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/meteora4.png"
    },
    {
        id:"ETHEREON",
        name:"ETHEREON",
        galaxy:"Andromeda-v",
        diameter:"ETHEREON",
        dayLength:"ETHEREON",
        avgTemperature:"ETHEREON",
        climate:"ETHEREON",
        src:"/meteora5.png"
    }


]